name: Daily Digest

on:
  schedule:
    - cron: '0 7 * * *'   # каждый день в 07:00 UTC
  workflow_dispatch:      # возможность запуска вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run digest script
       env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  CHANNEL_ID:     ${{ secrets.CHANNEL_ID }}
        run: python telegram-digest.py
